---
title: "advent of code - day 21"
author: "chad allison | 21 december 2022"
output: github_document
---

### loading packages

```{r message = F, warning = F}
library(tidyverse)
library(tidygraph)
options(scipen = 999)
```

### loading input data

```{r}
input = readLines("input.txt")
input[1:25]
```

### part 1

```{r}
input = tibble(x = input)
parsed = input |>
  extract(x, c("name", "yell"), regex = "(.*): (.*)") |>
  mutate(
    node_id = row_number(),
    expr = paste(name, yell, sep = " <- "))

nodes <- select(parsed, node_id, name)
edges <- parsed |>
  filter(is.na(as.integer(yell))) |>
  separate_rows(yell) |>
  select(from = yell, to = name)

g <- tbl_graph(nodes, edges)

nodes_in_topo_order <- g |>
  activate(nodes) |>
  mutate(topo_order = node_topo_order()) |>
  activate(nodes) |>
  as_tibble() |>
  arrange(topo_order)

exprs_in_topo_order <- nodes_in_topo_order |>
  left_join(parsed, by = "node_id") |>
  select(topo_order, expr) |>
  arrange(topo_order) |>
  deframe()

for (expr in exprs_in_topo_order) {
  eval(parse(text = expr))
}
root
```

### part 2

```{r warning = F, message = F}
parsed <- input |>
  extract(x, c("name", "yell"), regex = "(.*): (.*)") |>
  mutate(
    node_id = row_number(),
    expr = paste(name, yell, sep = " <- ")
  ) |>
  mutate(yell = case_when(
    name == "humn" ~ "humn",
    name == "root" ~ sub("\\+", "-", yell),
    TRUE ~ yell
  ))

nodes <- select(parsed, node_id, name)
edges <- parsed |>
  filter(is.na(as.integer(yell))) |>
  separate_rows(yell) |>
  select(from = name, to = yell)

g <- tbl_graph(nodes, edges)

nodes_in_topo_order <- g |>
  activate(nodes) |>
  mutate(topo_order = node_topo_order()) |>
  activate(nodes) |>
  as_tibble() |>
  arrange(topo_order)

exprs_in_topo_order <- nodes_in_topo_order |>
  left_join(parsed, by = c("node_id", "name")) |>
  arrange(topo_order) |>
  select(name, yell) |>
  deframe()

library(symengine)

vars <- lapply(parsed$name, as.name)
names(vars) <- parsed$name
do.call(use_vars, vars)

expr <- S(exprs_in_topo_order[["root"]])

for (var_name in names(exprs_in_topo_order)) {
  expr <- subs(expr, S(var_name), S(exprs_in_topo_order[[var_name]]))
  expr
}

solve(expr, "humn")
```

















































