---
title: "advent of code - day 7"
author: "chad allison | 7 december 2022"
output: github_document
---

### loading tidyverse

```{r message = F, warning = F}
library(tidyverse)
```

### loading input data

```{r}
input = readLines("day7_input.txt")

input[1:50]
```

### converting input into data frame

```{r}
df = data.frame(x = input)

head(df)
```

### creating function to determine current directory

```{r}
cd = function(path, dir) {
  
  if (!is.na(dir)) {
    
    if (dir == "..") {
      
      return(head(path, -1))
      
    }
    
    return(c(path, paste0(tail(path, 1), "/", dir)))
    
  }
  
  return(path)
  
}
```

### calculating directory sizes

```{r}
dir_sizes = df |>
  tidyr::extract(x, "cd_dir", "cd (.*)", remove = F) |>
  mutate(path = c(accumulate(cd_dir, cd))) |>
  unnest(path) |>
  filter(str_detect(x, "\\d")) |>
  separate(x, into = c("size", "file"), sep = " ", convert = T) |>
  group_by(path) |>
  summarise(size = sum(size))

head(dir_sizes)
```

### part 1 solution

```{r}
dir_sizes |>
  filter(size < 100000) |>
  summarise(size = sum(size)) |>
  pull(size)
```

### part 2 solution

```{r}
total_disk_space = 70000000
needed_space = 30000000

total_size = dir_sizes |>
  filter(path == "/") |>
  pull(size)

dir_sizes |>
  filter(size >= needed_space - (total_disk_space - total_size)) |>
  arrange(size) |>
  head(1) |>
  pull(size)
```



























