---
title: "advent of code - day 11"
author: "chad allison | 11 december 2022"
output: github_document
---

### loading tidyverse

```{r message = F, warning = F}
library(tidyverse)
```

### loading input data

```{r}
input = readLines("day11_input.txt")
input[1:28]
```

### formating the input as a data frame

```{r}
df = data.frame(x = input)
head(df)
```

### formatting data

```{r warning = F}
df = df |>
  mutate(monkey = ifelse(str_detect(x, "Monkey"), parse_number(x), NA),
         start = ifelse(str_detect(x, "Starting items"), str_remove(x, "Starting items:"), NA_real_),
         operation = ifelse(str_detect(x, "Operation"), str_remove(x, "Operation: "), NA),
         test = ifelse(str_detect(x, "Test"), parse_number(x), NA),
         next_true = ifelse(str_detect(x, "If true"), parse_number(x), NA),
         next_false = ifelse(str_detect(x, "If false"), parse_number(x), NA),
         x = NULL) |>
  fill(monkey) |>
  group_by(monkey) |>
  fill(everything(), .direction = "downup") |>
  ungroup() |>
  distinct() |>
  mutate(monkey = monkey + 1,
         next_true = next_true + 1,
         next_false = next_false + 1,
         start = strsplit(start, ",") |>
           map(as.numeric))

head(df)
```

### implementing logic for part 1

```{r}
do_operation = function(old, operation) {
  eval(parse(text = operation))
  return(new)
}

hold = df$start
insp_count = numeric(nrow(df))
round = 1

while (round <= 20) {
  for (monkey in df$monkey) {
    vals = do_operation(hold[[monkey]], df$operation[[monkey]])
    vals = floor(vals / 3)
    test = (vals %% df$test[[monkey]]) == 0
    next_true = df$next_true[monkey]
    next_false = df$next_false[monkey]
    hold[[next_true]] = c(hold[[next_true]], vals[test])
    hold[[next_false]] = c(hold[[next_false]], vals[!test])
    hold[[monkey]] = numeric()
    insp_count[monkey] = insp_count[monkey] + length(vals)
  }
  round = round + 1
}

insp_count
```

### part 1 solution

```{r}
sort(insp_count) |>
  tail(2) |>
  prod()
```

### recreating part 1 logic for part 2

```{r}
# we can use the same do_operation function

hold = df$start
insp_count = numeric(nrow(df))
round = 1

while (round <= 10000) {
  for (monkey in df$monkey) {
    vals = do_operation(hold[[monkey]], df$operation[[monkey]])
    test = (vals %% df$test[[monkey]]) == 0
    # modulo of vals by the product of tests
    vals = vals %% 9699690
    next_true = df$next_true[monkey]
    next_false = df$next_false[monkey]
    hold[[next_true]] = c(hold[[next_true]], vals[test])
    hold[[next_false]] = c(hold[[next_false]], vals[!test])
    hold[[monkey]] = numeric()
    insp_count[monkey] = insp_count[monkey] + length(vals)
  }
  round = round + 1
}
```

### part 2 solution

```{r}
sort(insp_count) |>
  tail(2) |>
  prod()
```

















































