---
title: "advent of code - day 8"
author: "chad allison | 8 december 2022"
output: github_document
---

### loading tidyverse

```{r message = F, warning = F}
library(tidyverse)
```

### loading input

```{r}
input = readLines("day8_input.txt")
input[1:10]
```

### formatting input data

```{r}
input = input |>
  sapply(\(x) as.integer(strsplit(x, "")[[1]])) |>
  unname()

input[1:3, ]
```

### creating matrices to track visible trees and keeping track of how many

```{r}
visibility = input ^ 0
score = input * 0

visibility[1:3, ]
score[1:3, ]
```

### implementing logic to determine which trees are visible

```{r}
for (i in 2:(nrow(input) - 1)) {
  for (j in 2:(ncol(input) - 1)) {
    surrounding_trees = list(input[i, 1:(j - 1)],
                             rev(input[i, (j + 1):ncol(input)]),
                             input[1:(i - 1), j],
                             rev(input[(i + 1):nrow(input), j]))
    
    visibility[i, j] = surrounding_trees |>
      sapply(\(x) max(x) < input[i, j]) |>
      any()
    
    score[i, j] = surrounding_trees |>
      lapply(\(x) cumsum(input[i, j] <= x)) |>
      sapply(\(x) sum(x == max(x))) |>
      prod()
  }
}
```

### part 1 solution

```{r}
sum(visibility)
```

### part 2 solution

```{r}
max(score)
```





















































