---
title: "advent of code - day 4"
author: "chad allison | 4 december 2022"
output: github_document
---

### loading tidyverse

```{r message = F, warning = F}
library(tidyverse)
```

### loading and previewing input data

```{r}
input = readLines("day4_input.txt")
df = data.frame(pairs = input)

head(df)
```

### splitting the pairs

```{r}
df = df |>
  separate(pairs, into = c("p1", "p2"), sep = ",")

head(df)
```

### further splitting the pairs

```{r}
df = df |>
  separate(p1, into = c("min1", "max1"), sep = "-") |>
  separate(p2, into = c("min2", "max2"), sep = "-") |>
  mutate_all(as.numeric)

head(df)
```

### determining how many pair ranges fully contain the other

```{r}
df = df |>
  mutate(p1_contains_p2 = ifelse(min1 <= min2 & max1 >= max2, 1, 0),
         p2_contains_p1 = ifelse(min2 <= min1 & max2 >= max1, 1, 0),
         same_pair = ifelse(min1 == min2 & max1 == max2, 1, 0))

head(df)
```

### part 1 solution

```{r}
sum(df$p1_contains_p2) + sum(df$p2_contains_p1) - sum(df$same_pair)
```

### creating variable for no overlap, then overlap

```{r}
df = df |>
  select(-same_pair) |>
  mutate(no_overlap = ifelse(max1 < min2 | min1 > max2, 1, 0),
         overlap = ifelse(no_overlap == 0, 1, 0))

head(df)
```

### part 2 solution

```{r}
sum(df$overlap)
```



































