---
title: "advent of code - day 13"
author: "chad allison | 13 december 2022"
output: github_document
---

### loading tidyverse

```{r message = F, warning = F}
library(tidyverse)
library(glue)
library(here)
```

### loading input data

```{r}
input = data.frame(x = readLines("day13_input.txt"))

input |>
  pull(x) |>
  head(5)
```

### creating function to determine if values are ordered or not

```{r}
compare = function(x, y) {
  if (is.numeric(x) & is.numeric(y)) {
    return(sign(y - x))
  }
  if (!is.list(x)) x = list(x)
  if (!is.list(y)) y = list(y)
  for (i in seq_len(length(x))) {
    if (i > length(y)) {
      return(-1) # wrong order
    }
    cmp = compare(x[[i]], y[[i]])
    if (cmp != 0) {
      return(cmp)
    }
  }
  if (length(x) == length(y)) {
    return(0) # check next
  }
  return(1) # right order
}
```

### collecting data packets

```{r}
packets = input |>
  mutate(x = str_replace_all(x, "\\[", "list("),
         x = str_replace_all(x, "\\]", ")"),
         pair = cumsum(x == "") + 1) |>
  filter(x != "") |>
  mutate(packet = map(x, ~ eval(parse(text = .))))

packets |>
  select(pair, packet) |>
  head()
```

### comparing pairs

```{r}
packets_evaluated = packets |>
  group_by(pair) |>
  summarise(packet1 = packet[1],
            packet2 = packet[2]) |>
  mutate(cmp = map2_dbl(packet1, packet2, compare))
```

### part 1 solution

```{r}
packets_evaluated |>
  filter(cmp == 1) |>
  summarise(sum = sum(pair)) |>
  pull(sum)
```

### identifying where dividers sit

```{r}
packets_evaluated = packets |>
  mutate(div1 = map_dbl(packet, compare, list(list(2))),
         div2 = map_dbl(packet, compare, list(list(6))))
```

### part 2 solution

```{r}
packets_evaluated |>
  summarise(position_divider_1 = sum(div1 == 1) + 1,
            position_divider_2 = sum(div2 == 1) + 2,
            prod = position_divider_1 * position_divider_2) |>
  pull(prod)
```













































